set(WITH_QT ON CACHE BOOL "")
set(WITH_OPENGL ON CACHE BOOL "")
set(BUILD_TESTS OFF CACHE BOOL "")
set(BUILD_TESTING OFF CACHE BOOL "")
set(BUILD_PERF_TESTS OFF CACHE BOOL "")
set(BUILD_EXAMPLES OFF CACHE BOOL "")


